version: '3'

services:
  mysql-db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    command: [--ignore-db-dir=lost+found]
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "login"
    volumes:
      - ./src:/var/lib/mysql

  php-app:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql-db
